image: docker:19.03.1

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/oon/calendar .
    - docker push $CI_REGISTRY/oon/calendar