apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
spec:
  selector:
    matchLabels:
      app: calendar
  replicas: 1
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
      - name: calendar
        image: registry.lab.elm.sh/oon/calendar:latest
        ports:
        - containerPort: 5997
---
apiVersion: v1
kind: Service
metadata:
  name: calendar
spec:
  selector:
    app: calendar
  ports:
    - protocol: TCP
      port: 5997
      targetPort: 5997